In [1]:
import numpy as np

In [12]:
a1=np.random.randint(2,5,size=(2,4,2))
a1

array([[[2, 4],
        [3, 4],
        [3, 2],
        [4, 2]],

       [[3, 3],
        [2, 2],
        [3, 4],
        [4, 2]]])

In [7]:
np.array([1,2,3])

array([1, 2, 3])

In [28]:
a2=np.array([[[1,2,3]],
         [[4,5,6]]])

In [31]:
a2.ndim

3

In [33]:
a4=np.array([[1,2,3],
            [2,5,6]])
a4.ndim

2

In [18]:
a3=np.array([[[[1,2,3],
        [2,3,4]]],
        [[[3,1,2],
        [4,5,6]]],
        [[[8,5,6],
        [9,4,3]]]])
a3

array([[[[1, 2, 3],
         [2, 3, 4]]],


       [[[3, 1, 2],
         [4, 5, 6]]],


       [[[8, 5, 6],
         [9, 4, 3]]]])

In [21]:
a3.shape

(3, 1, 2, 3)

In [22]:
import pandas as pd


In [35]:
#create dataframe
sales=pd.DataFrame(a4)
sales

0  1  2
0  1  2  3
1  2  5  6

In [40]:
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
zeros=np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [44]:
zeros.ndim,zeros.shape

(3, (7, 2, 3))

In [46]:
b=np.array([1,100,3])

In [47]:
b

array([  1, 100,   3])

In [48]:
a6=np.arange(0,100,3)

In [49]:
a6

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [52]:
a7=np.random.randint(0,10,size=(7,2))
a7

array([[3, 2],
       [4, 9],
       [6, 3],
       [1, 5],
       [8, 8],
       [6, 0],
       [4, 3]])

In [55]:
a8=np.random.random((3,5))
a8

array([[0.48432898, 0.84623061, 0.53987073, 0.46814028, 0.69914924],
       [0.36164319, 0.82232034, 0.73617491, 0.60506378, 0.90160668],
       [0.68806448, 0.17915255, 0.3557365 , 0.59677372, 0.0571006 ]])

In [56]:
a3

array([[[[1, 2, 3],
         [2, 3, 4]]],


       [[[3, 1, 2],
         [4, 5, 6]]],


       [[[8, 5, 6],
         [9, 4, 3]]]])